"""add generation_cache table

Revision ID: 608634bc0d65
Revises: a9ac25803428
Create Date: 2026-04-22 08:43:02.386551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608634bc0d65'
down_revision: Union[str, Sequence[str], None] = 'a9ac25803428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_hit_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_generation_cache_key')
    )
    op.create_index(op.f('ix_generation_cache_cache_key'), 'generation_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_generation_cache_created_at'), 'generation_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_cache_id'), 'generation_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_cache_id'), table_name='generation_cache')
    op.drop_index(op.f('ix_generation_cache_created_at'), table_name='generation_cache')
    op.drop_index(op.f('ix_generation_cache_cache_key'), table_name='generation_cache')
    op.drop_table('generation_cache')
    # ### end Alembic commands ###
