export const routes = {
  today: "/dashboard",
  courses: "/projects",
  calendar: "/calendar",
  newCourse: "/projects/new",
  dashboard: "/dashboard",
  projects: "/projects",
  newProject: "/projects/new",
  templates: "/template",
  settings: "/settings",
  account: "/settings/account",
  billing: "/settings/billing",
  projectOverview: (projectId: string) => `/projects/${projectId}`,
  projectReviewer: (projectId: string) => `/projects/${projectId}/reviewer`,
  projectSources: (projectId: string) => `/projects/${projectId}/sources`,
  projectStream: (projectId: string) => `/projects/${projectId}/stream`,
  projectPlanning: (projectId: string) => `/projects/${projectId}/planning`,
  projectSettings: (projectId: string) => `/projects/${projectId}/settings`,
  projectExport: (projectId: string) => `/projects/${projectId}/reviewer/export`,
  courseOverview: (courseId: string) => `/projects/${courseId}`,
  courseNotebook: (courseId: string) => `/projects/${courseId}/reviewer`,
  courseMaterials: (courseId: string) => `/projects/${courseId}/sources`,
  courseRoom: (courseId: string) => `/projects/${courseId}/stream`,
  coursePlan: (courseId: string) => `/projects/${courseId}/planning`,
  courseSettings: (courseId: string) => `/projects/${courseId}/settings`,
  projectNotebook: (projectId: string) => `/projects/${projectId}/notebook`,
  courseExams: (courseId: string) => `/projects/${courseId}/exams`,
  courseExamSession: (courseId: string, examId: string) =>
    `/projects/${courseId}/exams/${examId}`,
};
