// Common subject areas for the "Add a course" wizard autocomplete. Free-text is
// still allowed — this list only powers suggestions via a native <datalist>.
export const SUBJECT_SUGGESTIONS = [
  "Accounting",
  "Anatomy",
  "Anthropology",
  "Architecture",
  "Biochemistry",
  "Biology",
  "Business Administration",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "Geography",
  "History",
  "Information Technology",
  "Law",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology",
  "Statistics",
] as const;
